package tp1.api.service.rest;

import jakarta.ws.rs.Consumes;
import jakarta.ws.rs.DELETE;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.HeaderParam;
import jakarta.ws.rs.POST;
import jakarta.ws.rs.PUT;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.PathParam;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.QueryParam;
import jakarta.ws.rs.core.MediaType;
import tp1.api.Spreadsheet;

@Path(RestSpreadsheets.PATH)
public interface ReplicationRestSpreadsheets extends RestSpreadsheets{
	
	public static final String DELETESHEETS = "/deleteSheets";
	public static final String OPERATION = "/operation";
	public static final String PRIMARY = "/primary";
	public static final String TASKS = "/tasks";
	
	/**
	 * Creates a new spreadsheet. The sheetId and sheetURL are generated by the server.
	 * After being created, the size of the spreadsheet is not modified.
	 * 
	 * @param sheet - the spreadsheet to be created.
	 * @param repSecret - secret sent by the primary to the secondaries that serves as authentication
	 * @param version - version of the client that started the execution of the operation
	 * 
	 */
	@POST
	@Path(OPERATION)
	@Consumes(MediaType.APPLICATION_JSON)
	@Produces(MediaType.APPLICATION_JSON)
	String createSpreadsheetOperation(Spreadsheet sheet, @QueryParam("repSecret") String repSecret, @HeaderParam(HEADER_VERSION) Long version);

	/**
	 * Deletes a spreadsheet.  Only the owner can call this method.
	 * 
	 * @param sheetId - the sheet to be deleted.
	 * @param repSecret - secret sent by the primary to the secondaries that serves as authentication
	 * @param version - version of the client that started the execution of the operation
	 * 
	 */
	@DELETE
	@Path("/{sheetId}" + OPERATION)
	void deleteSpreadsheetOperation(@PathParam("sheetId") String sheetId, @QueryParam("repSecret") String repSecret, @HeaderParam(HEADER_VERSION) Long version);
		
	/**
	 * Updates the raw values of some cells of a spreadsheet. 
	 * 
	 * @param userId - The user performing the update.
	 * @param sheetId - the spreadsheet whose values are being retrieved.
	 * @param cell - the cell being updated
	 * @param rawValue - the new raw value of the cell
	 * @param password - the password of the owner of the spreadsheet
	 * @param repSecret - secret sent by the primary to the secondaries that serves as authentication
	 * @param version - version of the client that started the execution of the operation
	 * 
	 */
	@PUT
	@Path("/{sheetId}/{cell}" + OPERATION)
	@Consumes(MediaType.APPLICATION_JSON)
	void updateCellOperation( @PathParam("sheetId") String sheetId, @PathParam("cell") String cell, String rawValue, @QueryParam("repSecret") String repSecret, @HeaderParam(HEADER_VERSION) Long version);
	
	/**
	 * Adds a new user to the list of shares of a spreadsheet. Only the owner can call this method.
	 * 
	 * @param sheetId - the sheet being shared.
	 * @param userId - the user that is being added to the list of shares. In this method, the userId is represented
	 *                 in the form userId@domain
	 * @param repSecret - secret sent by the primary to the secondaries that serves as authentication 
	 * @param version - version of the client that started the execution of the operation
	 *  
	 */
	@POST
	@Path("/{sheetId}/share/{userId}" + OPERATION)
	void shareSpreadsheetOperation( @PathParam("sheetId") String sheetId, @PathParam("userId") String userId, @QueryParam("repSecret") String repSecret, @HeaderParam(HEADER_VERSION) Long version);
	
	/**
	 * Removes a user from the list of shares of a spreadsheet. Only the owner can call this method.
	 * 
	 * @param sheetId - the sheet being shared.
	 * @param userId - the user that is being added to the list of shares. In this method, the userId is represented
	 *                 in the form userId@domain
	 * @param repSecret - secret sent by the primary to the secondaries that serves as authentication
	 * @param version - version of the client that started the execution of the operation
	 * 
	 */
	@DELETE
	@Path("/{sheetId}/share/{userId}" + OPERATION)
	void unshareSpreadsheetOperation( @PathParam("sheetId") String sheetId, @PathParam("userId") String userId, @QueryParam("repSecret") String repSecret, @HeaderParam(HEADER_VERSION) Long version);
	
	/**
	 * Removes all the Spreadsheets from the service that belong to the userId
	 * @param userId - the userId who's sheets shall be forgotten
	 * @param repSecret - secret sent by the primary to the secondaries that serves as authentication
	 * @param version - version of the client that started the execution of the operation
	 * 
	 */
	@DELETE
	@Path(DELETESHEETS + "/{userId}" + OPERATION)
	void deleteUserSpreadsheetsOperation(@PathParam("userId") String userId, @QueryParam("repSecret") String repSecret, @HeaderParam(HEADER_VERSION) Long version);
	
	/*
	 * Notifies a server that he is now the primary server and must update it's content
	 * 
	 * @param repSecret - secret sent by the primary to the secondaries that serves as authentication
	 * @param version - version of the client that started the execution of the operation
	 * 
	 */
	@POST
	@Path(PRIMARY)
	void primaryNodeNotification(@QueryParam("repSecret") String repSecret);

	/*
	 * Gets the list of executed Tasks from the server
	 * 
	 * @param repSecret - secret sent by the primary to the secondaries that serves as authentication
	 * @param version - version of the client that started the execution of the operation
	 * 
	 */
	@GET
	@Path(TASKS)
	String getExecutedTasks(@QueryParam("startingPos") int startingPos, @QueryParam("repSecret") String repSecret);
}
